version: "3.7"
services:
  hydra:
    image: oryd/hydra:v2.2.0-rc.3
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5556:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: bind
        source: ./docker/hydra
        target: /etc/config/hydra
    environment:
      - DSN=mysql://root:root@tcp(hydra-mysql:3306)/mysql?max_conns=20&max_idle_conns=4
    restart: unless-stopped
    # depends_on:
    #   - hydra-migrate
    networks:
      - intranet

  hydra-migrate:
    image: oryd/hydra:v2.2.0-rc.3
    environment:
      - DSN=mysql://root:root@tcp(hydra-mysql:3306)/mysql?max_conns=20&max_idle_conns=4
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: bind
        source: ./docker/hydra
        target: /etc/config/hydra
    restart: on-failure
    depends_on:
      - hydra-mysql
    networks:
      - intranet
    
  kratos-migrate:
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=mysql://root:root@tcp(kratos-mysql:3306)/mysql?max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./docker/kratos/config/kratos
        target: /etc/config/kratos
    command: migrate sql -e --yes
    depends_on:
      - kratos-mysql
    networks:
      - intranet

  kratos:
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=mysql://root:root@tcp(kratos-mysql:3306)/mysql?max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
      - TRACING_PROVIDER=jaeger
      - TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL=http://jaeger:5778/sampling
      - TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS=jaeger:6831
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    command: serve --dev -c /etc/config/kratos/kratos.yml --watch-courier
    volumes:
      - type: bind
        source: ./docker/kratos/config/kratos
        target: /etc/config/kratos
    networks:
      - intranet

  jaeger:
    image: jaegertracing/all-in-one:1.51.0
    ports:
      - "16686:16686" # The UI port
    networks:
      - intranet

  hydra-mysql:
    image: mysql:8.2.0
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: hydra-mysql
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    networks:
      - intranet

  kratos-mysql:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: kratos-mysql
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    networks:
      - intranet
  
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    platform: linux/x86_64
    ports:
      - '1025:1025'
      - '4436:4436'
      - '4437:4437'

networks:
  intranet:

volumes:
  hydra-mysql:
  kratos-mysql: