server:
  version: v1
  port: 8080
  cors:
    allowed_origins:
      - http://localhost:3000
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed_headers:
      - Content-Type
      - Accept
      - Authorization
      - X-Requested-With
      - Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
    exposed_headers:
      - Content-Type
      - Accept
      - Authorization
      - X-Requested-With
      - Origin
      - Access-Control-Request-Method
      - Access-Control-Request-Headers
    allow_credentials: true
    max_age: 1728000